"""baseline schema (Phase 3 + Feishu hooks)

Revision ID: f8540d2f6dcd
Revises: 
Create Date: 2026-05-23 21:27:25.564799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8540d2f6dcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code', name='uq_dict_category_code')
    )
    op.create_index(op.f('ix_data_dict_category'), 'data_dict', ['category'], unique=False)
    op.create_table('need_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('party_type', sa.String(length=32), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_parties_name'), 'need_parties', ['name'], unique=True)
    op.create_table('sales_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_persons_name'), 'sales_persons', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('feishu_open_id', sa.String(length=64), nullable=True),
    sa.Column('feishu_union_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_feishu_open_id'), 'users', ['feishu_open_id'], unique=False)
    op.create_index(op.f('ix_users_feishu_union_id'), 'users', ['feishu_union_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('cooperation_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_table('engineers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('employment_form', sa.String(length=32), nullable=False),
    sa.Column('labor_company', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('english_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('id_doc_type', sa.String(length=16), nullable=True),
    sa.Column('id_doc_number_enc', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('monthly_cost_to_telecom', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_real_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineers_full_name'), 'engineers', ['full_name'], unique=False)
    op.create_index(op.f('ix_engineers_vendor_id'), 'engineers', ['vendor_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=32), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_logs_event_type'), 'notification_logs', ['event_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('need_party_id', sa.Integer(), nullable=False),
    sa.Column('sales_person_id', sa.Integer(), nullable=False),
    sa.Column('pm_user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('outsource_benchmark_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('benchmark_basis', sa.String(length=32), nullable=True),
    sa.Column('benchmark_basis_note', sa.Text(), nullable=True),
    sa.Column('value_created_basis', sa.String(length=32), nullable=True),
    sa.Column('value_created_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('district', sa.String(length=16), nullable=True),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('renewal_of_project_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['need_party_id'], ['need_parties.id'], ),
    sa.ForeignKeyConstraint(['pm_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['renewal_of_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sales_person_id'], ['sales_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_district'), 'projects', ['district'], unique=False)
    op.create_index(op.f('ix_projects_kind'), 'projects', ['kind'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_need_party_id'), 'projects', ['need_party_id'], unique=False)
    op.create_index(op.f('ix_projects_renewal_of_project_id'), 'projects', ['renewal_of_project_id'], unique=False)
    op.create_index(op.f('ix_projects_sales_person_id'), 'projects', ['sales_person_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('allocation_ratio', sa.Integer(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_engineer_id'), 'assignments', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_assignments_project_id'), 'assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=True),
    sa.Column('cert_number', sa.String(length=128), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_engineer_id'), 'certificates', ['engineer_id'], unique=False)
    op.create_table('engineer_skill_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('skill_count', sa.Integer(), nullable=False),
    sa.Column('avg_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('cert_count', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineer_id', 'snapshot_date', name='uq_eng_snapshot_date')
    )
    op.create_index(op.f('ix_engineer_skill_snapshots_engineer_id'), 'engineer_skill_snapshots', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_engineer_skill_snapshots_snapshot_date'), 'engineer_skill_snapshots', ['snapshot_date'], unique=False)
    op.create_table('engineer_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineer_id', 'skill_id', name='uq_engineer_skill')
    )
    op.create_index(op.f('ix_engineer_skills_engineer_id'), 'engineer_skills', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_engineer_skills_skill_id'), 'engineer_skills', ['skill_id'], unique=False)
    op.create_table('expense_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('expense_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_requests_expense_type'), 'expense_requests', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expense_requests_project_id'), 'expense_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_status'), 'expense_requests', ['status'], unique=False)
    op.create_table('idps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('target_skills', sa.Text(), nullable=True),
    sa.Column('target_certs', sa.Text(), nullable=True),
    sa.Column('plan_actions', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idps_engineer_id'), 'idps', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_idps_status'), 'idps', ['status'], unique=False)
    op.create_table('knowledge_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('confidentiality', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_assets_category'), 'knowledge_assets', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_confidentiality'), 'knowledge_assets', ['confidentiality'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_title'), 'knowledge_assets', ['title'], unique=False)
    op.create_table('project_retrospectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('satisfaction_score', sa.Integer(), nullable=False),
    sa.Column('what_went_well', sa.Text(), nullable=True),
    sa.Column('what_to_improve', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_retrospectives_project_id'), 'project_retrospectives', ['project_id'], unique=False)
    op.create_table('project_revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('recognized_date', sa.Date(), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_revenues_project_id'), 'project_revenues', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_revenues_recognized_date'), 'project_revenues', ['recognized_date'], unique=False)
    op.create_table('renewal_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_project_id', sa.Integer(), nullable=False),
    sa.Column('attempt_date', sa.Date(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('won_project_id', sa.Integer(), nullable=True),
    sa.Column('lost_reason', sa.String(length=32), nullable=True),
    sa.Column('lost_reason_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['won_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_attempts_outcome'), 'renewal_attempts', ['outcome'], unique=False)
    op.create_index(op.f('ix_renewal_attempts_previous_project_id'), 'renewal_attempts', ['previous_project_id'], unique=False)
    op.create_table('sales_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_sales_person_id', sa.Integer(), nullable=False),
    sa.Column('to_sales_person_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('operator_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_sales_person_id'], ['sales_persons.id'], ),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_sales_person_id'], ['sales_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transfer_logs_project_id'), 'sales_transfer_logs', ['project_id'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_engineer_id'), 'training_records', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_training_records_training_date'), 'training_records', ['training_date'], unique=False)
    op.create_table('vendor_service_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_service_fees_vendor_id'), 'vendor_service_fees', ['vendor_id'], unique=False)
    op.create_table('asset_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('estimated_hours_saved', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('referenced_by_user_id', sa.Integer(), nullable=True),
    sa.Column('referenced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['referenced_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_references_asset_id'), 'asset_references', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_references_project_id'), 'asset_references', ['project_id'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('person_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineer_id', 'project_id', 'work_date', name='uq_ts_eng_proj_date')
    )
    op.create_index(op.f('ix_timesheets_engineer_id'), 'timesheets', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_timesheets_project_id'), 'timesheets', ['project_id'], unique=False)
    op.create_index(op.f('ix_timesheets_work_date'), 'timesheets', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_work_date'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_project_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_engineer_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_asset_references_project_id'), table_name='asset_references')
    op.drop_index(op.f('ix_asset_references_asset_id'), table_name='asset_references')
    op.drop_table('asset_references')
    op.drop_index(op.f('ix_vendor_service_fees_vendor_id'), table_name='vendor_service_fees')
    op.drop_table('vendor_service_fees')
    op.drop_index(op.f('ix_training_records_training_date'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_engineer_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_sales_transfer_logs_project_id'), table_name='sales_transfer_logs')
    op.drop_table('sales_transfer_logs')
    op.drop_index(op.f('ix_renewal_attempts_previous_project_id'), table_name='renewal_attempts')
    op.drop_index(op.f('ix_renewal_attempts_outcome'), table_name='renewal_attempts')
    op.drop_table('renewal_attempts')
    op.drop_index(op.f('ix_project_revenues_recognized_date'), table_name='project_revenues')
    op.drop_index(op.f('ix_project_revenues_project_id'), table_name='project_revenues')
    op.drop_table('project_revenues')
    op.drop_index(op.f('ix_project_retrospectives_project_id'), table_name='project_retrospectives')
    op.drop_table('project_retrospectives')
    op.drop_index(op.f('ix_knowledge_assets_title'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_confidentiality'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_category'), table_name='knowledge_assets')
    op.drop_table('knowledge_assets')
    op.drop_index(op.f('ix_idps_status'), table_name='idps')
    op.drop_index(op.f('ix_idps_engineer_id'), table_name='idps')
    op.drop_table('idps')
    op.drop_index(op.f('ix_expense_requests_status'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_project_id'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_expense_type'), table_name='expense_requests')
    op.drop_table('expense_requests')
    op.drop_index(op.f('ix_engineer_skills_skill_id'), table_name='engineer_skills')
    op.drop_index(op.f('ix_engineer_skills_engineer_id'), table_name='engineer_skills')
    op.drop_table('engineer_skills')
    op.drop_index(op.f('ix_engineer_skill_snapshots_snapshot_date'), table_name='engineer_skill_snapshots')
    op.drop_index(op.f('ix_engineer_skill_snapshots_engineer_id'), table_name='engineer_skill_snapshots')
    op.drop_table('engineer_skill_snapshots')
    op.drop_index(op.f('ix_certificates_engineer_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_project_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_engineer_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_sales_person_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_renewal_of_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_need_party_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_kind'), table_name='projects')
    op.drop_index(op.f('ix_projects_district'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notification_logs_event_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_engineers_vendor_id'), table_name='engineers')
    op.drop_index(op.f('ix_engineers_full_name'), table_name='engineers')
    op.drop_table('engineers')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_feishu_union_id'), table_name='users')
    op.drop_index(op.f('ix_users_feishu_open_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_sales_persons_name'), table_name='sales_persons')
    op.drop_table('sales_persons')
    op.drop_index(op.f('ix_need_parties_name'), table_name='need_parties')
    op.drop_table('need_parties')
    op.drop_index(op.f('ix_data_dict_category'), table_name='data_dict')
    op.drop_table('data_dict')
    # ### end Alembic commands ###
